name: Android 16 Native Build

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test runner
        run: |
          echo "Target: SM-G610F / on7xelte"
          echo "Build type: Native"
          echo "GSI: NO"
          echo "DSU: NO"
          echo "Runner is working!"
          
